<?php
function array_random($arr, $num = 1) {
	shuffle($arr);
	
	$r = array();
	for ($i = 0; $i < $num; $i++) {
		$r[] = $arr[$i];
	}
	return $num == 1 ? $r[0] : $r;
}

$a = array(

"\"My son is sucking me dry.\" -Weest 2017"
"\Lemme see that cock.\" -Weest 2017"
"\Yo you eat ass?\" -Weest 2017"
"\I am gonna fuck this little girl.\" -Weest 2017"
"\Why cross the street when you can cut your meat?\" -Weest 2017"
"\Everybody clap your hands! Clap clap clap clap this is how my dick sounds when I'm in the bath cause my roommate sleeps below me and I cannot masturbate.\" -Weest 2017"
"\He fuckin' made the alalalala!\" -Weest 2017"
"\You aint slippin past me, fuck boi.\" -Weest 2017"
"\Is that a dick?!\" -Weest 2017"

);
print_r(array_random($a));
?>